
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    env_file:
      - ./src/.env.${APP_ENV} # carrega as variáveis do Laravel
    volumes:
      - ./src:/var/www
    environment: 
      APP_ENV: ${APP_ENV} 
      APP_DEBUG: ${APP_DEBUG} 
      APP_KEY: ${APP_KEY} 
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT} 
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE} 
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_STORE: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
    working_dir: /var/www
    networks:
      - laravel-net
    
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80
    depends_on:
      - php
      - mysql
    networks:
      - laravel-net
  
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel-net

  react: 
    build: 
      context: .
      dockerfile: docker/react/Dockerfile
    container_name: laravel_react
    ports: 
      - "${REACT_APP_PORT}:3000"
    volumes: 
      - ./app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - laravel-net

volumes:
  dbdata:

networks:
  laravel-net:
    driver: bridge